[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd convertiverse-backend && npm install"]

[phases.build]
cmds = ["cd convertiverse-backend && npm install"]

[start]
cmd = "cd convertiverse-backend && npm start"
